### ISSUE TITLE
[Suggestion] Update project settings so it rejects warnings in dotnet test

### ISSUE THREAD

**Issue by Abastro** [KAIST-CS220/2020s-activities#2]
Hello professor,
As the server rejects submissions when there are warnings, I'd like it if we also get failed message in dotnet test on warnings.

**Comment by sangkilc** [comment]
Thanks for the reminder. You will see warnings from the next activities :)

**Comment by sangkilc** [comment]
f715c774dd5fec89af50087caa3cf5b811a966a8
